version: "3.8"
services:
  app:
    build: ./infra/php
    volumes:
      - ./backend:/work

  web:
    image: nginx:1.18-alpine
    ports:
      - 8080:80
    volumes:
      - ./backend:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work
  
  nodejs:
    image: node:13.8-alpine
    volumes:
      - ./backend:/work:cached
    working_dir: /work
    tty: true

  db:
    build: ./infra/mysql
    volumes:
      - db-store:/var/lib/mysql
  
  db-test:
    build: ./infra/mysql

volumes:
  db-store: