version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.4-node-browsers
        environment:
        - DB_HOST: 127.0.0.1
        - DB_PORT: 3306
        - DB_DATABASE: rs
        - DB_USERNAME: phper
        - DB_PASSWORD: secret
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_DATABASE: rs
          - MYSQL_USER: phper
          - MYSQL_ROOT_PASSWORD: secret
    steps:
      - checkout
      - run: sudo apt update
      - run: sudo docker-php-ext-install zip pdo_mysql
      - run: sudo composer self-update --1
      - run: 
          working_directory: backend
          command: composer install -n --prefer-dist
      - run: 
          working_directory: backend
          command: npm ci
      - run: 
          working_directory: backend
          command: npm run dev
      - run:
          working_directory: backend
          name: php test
          command: vendor/bin/phpunit